logging:
  level:
    root: info

server:
  shutdown: graceful

spring:
  main:
    web-application-type: none
  rsocket:
    server:
      port: 7002

---

spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reddit-clone

oauth2:
  resource-server:
    oidc-issuer-location: http://localhost:8080/auth/realms/reddit-clone